### ISSUE TITLE
提供一个部署在vercel的方法

### ISSUE THREAD

**Issue by ZihaoFeng2001** [rockbenben/LearnData#1]
直接在vercel导入你的repo，部署之后（此时部署是失败的）去settings把production branch改成gh-pages即可。需要更新一下仓库内容触发部署。vercel目前国内访问速度很不错。ps：FRAMEWORK PRESET这里选others即可

**Comment by rockbenben** [comment]
> 直接在vercel导入你的repo，部署之后（此时部署是失败的）去settings把production branch改成gh-pages即可。需要更新一下仓库内容触发部署。vercel目前国内访问速度很不错。ps：FRAMEWORK PRESET这里选others即可

测试了速度确实不错，晚点把你的建议补充在部署步骤里

**Comment by dselegent** [comment]
> 直接在vercel导入你的repo，部署之后（此时部署是失败的）去settings把production branch改成gh-pages即可。需要更新一下仓库内容触发部署。vercel目前国内访问速度很不错。ps：FRAMEWORK PRESET这里选others即可

现在国内访问不了
