### ISSUE TITLE
您好，我想问一下，这个部署过程中，没找到“gh-page branch”,上传了新的文件（不懂这算不算修改任意文件），还是没显示，怎么办.....

### ISSUE THREAD

**Issue by Spartanmans** [rockbenben/LearnData#11]
没找到“gh-page branch”, 也没有绿色的“Your site is published at” 提示访问链接 出现
![image](https://user-images.githubusercontent.com/39773354/224716886-82a1721c-733a-48a5-9743-3755b6dd1e6b.png)
![image](https://user-images.githubusercontent.com/39773354/224717173-f534ab3f-68d2-449d-8cef-2c72b0bd6b8c.png)

**Comment by rockbenben** [comment]
新版 GitHub 需要权限，按常见问题- failed with exit code 128 来解决

进入项目仓库的「Settings」>「Code and automation」>「Actions」>「General」，选中底部 Workflow permissions 中的 `Read and write permissions`，点击保存后重新部署即可。

**Comment by Spartanmans** [comment]
> 新版 GitHub 需要权限，按常见问题- failed with exit code 128 来解决
> 
> 进入项目仓库的「Settings」>「Code and automation」>「Actions」>「General」，选中底部 Workflow permissions 中的 `Read and write permissions`，点击保存后重新部署即可。

好的，我再试一下
