### ISSUE TITLE
> > 新版 GitHub 需要权限，按常见问题- failed with exit code 128 来解决

### ISSUE THREAD

**Issue by Spartanmans** [rockbenben/LearnData#12]
> > 新版 GitHub 需要权限，按常见问题- failed with exit code 128 来解决
> > 进入项目仓库的「Settings」>「Code and automation」>「Actions」>「General」，选中底部 Workflow permissions 中的 `Read and write permissions`，点击保存后重新部署即可。
> 
> 好的，我再试一下

看了你的仓库。不要点 GitHub Action 来部署 Pages，会污染网页。你按下列步骤执行下。

进入「Actions」>「最新的 workflow」，然后点击右上方的「Re-run all jobs」，重新生成网页。部署正确的话 GitHub 会自动搭建网站。

_Originally posted by @rockbenben in https://github.com/rockbenben/LearnData/issues/11#issuecomment-1466214405_

不好意思，感觉好麻瓜 ....不确定有没有操作对.....
![128e05ed0df25b93334537c22b95628](https://user-images.githubusercontent.com/39773354/224733015-30001e69-b691-4818-8d26-f800434bdcfa.png)

![image](https://user-images.githubusercontent.com/39773354/224733215-99691eff-03af-4c24-901e-a4847eafe45a.png)

这算.....是....成功了吗 
![image](https://user-images.githubusercontent.com/39773354/224733993-4e0d00da-abc2-457c-957c-5058dafbdf1f.png)

![image](https://user-images.githubusercontent.com/39773354/224733655-fed0b83b-d07c-4cf7-9737-9ce52b14f500.png)

**Comment by rockbenben** [comment]
对的，在按后面的步骤修改就行：

> 点击「Settings」, 修改 `Repository name` 为 `xxx.github.io`, `xxx` 是你的 GitHub 用户名。如果该项名称已被占据，GitHub Pages 无法正常显示，则查看页面底部的常见问题。

搭建步骤看来还不够清晰，我来修改一下。

**Comment by Spartanmans** [comment]
> 对的，在按后面的步骤修改就行，你的仓库名应该设为 spartanmans.github.io
> 
> > 点击「Settings」, 修改 `Repository name` 为 `xxx.github.io`, `xxx` 是你的 GitHub 用户名。如果该项名称已被占据，GitHub Pages 无法正常显示，则查看页面底部的常见问题。
> 
> 搭建步骤看来还不够清晰，我来修改一下。

已经部署成功了，非常感谢
