### ISSUE TITLE
使用vercel部署时遇到一些问题

### ISSUE THREAD

**Issue by youth54** [rockbenben/LearnData#2]
非常感谢您提供的这个网页模板和部署教程，整个过程都很详细。
但是我在使用vercel部署时遇到了一些错误，具体如下：
![image](https://user-images.githubusercontent.com/72968849/188262973-a31659fc-4d70-4277-b60a-e9ed1e7387e0.png)
![image](https://user-images.githubusercontent.com/72968849/188263002-cf57f86d-706b-4026-82a1-ccf518c3d766.png)

看错误提示，感觉是在main.yml中加入的`Copy file to Vercel`脚本出现了错误，但是我对yml语言不太懂，请教一下，这个问题该如何解决呢？

**Comment by rockbenben** [comment]
检查访问令牌权限是否有勾选 repo

- 新建 [个人访问令牌](https://github.com/settings/tokens)，勾选权限「repo Full control of private repositories」，生成后复制 token 值。
- 进入项目仓库的「setting - Secrets - Action」，新建密钥 PERSONAL_TOKEN，并填入刚复制的 token 值。

**Comment by youth54** [comment]
OK，已经可以正常运行了。非常感谢！
