### ISSUE TITLE
关于看板娘跨域的问题

### ISSUE THREAD

**Issue by wh9204** [rockbenben/LearnData#3]
作者您好 首先很感谢您分享的精美模板，在Github pages使用发现调用您的看板娘API产生了跨域的问题，请问有什么比较好的方式解决么

**Comment by rockbenben** [comment]
按 [常见问题](https://newzone.top/#%E7%9C%8B%E6%9D%BF%E5%A8%98%E4%B8%8D%E6%98%BE%E7%A4%BA%E5%9B%BE%E5%83%8F) 中的「看板娘不显示图像」修改下

**Comment by wh9204** [comment]
@rockbenben 感谢，只看了部署部分 没看到常见问题~

**Comment by rockbenben** [comment]
> @rockbenben 感谢，只看了部署部分 没看到常见问题~

修改了，把它从常见问题提到部署页，之前确实不够清楚
