### ISSUE TITLE
请问这是什么问题

### ISSUE THREAD

**Issue by shenzehui** [rockbenben/LearnData#5]
![image](https://user-images.githubusercontent.com/86279988/199658422-296513af-af5f-49b6-a884-8e1d8b3d9fda.png)

**Comment by rockbenben** [comment]
package.json 修改了，但 pnpm-lock.yaml 并未更新，导致环境依赖缺失。

最简单的方法是，本地执行 `pnpm i`，pnpm-lock.yaml 会全面更新。

**Comment by shenzehui** [comment]
@rockbenben 原来如此，感谢！
