### ISSUE TITLE
又来了，打包错误

### ISSUE THREAD

**Issue by shenzehui** [rockbenben/LearnData#6]
![image](https://user-images.githubusercontent.com/86279988/199670241-61078fe3-55ae-48bd-8a20-82818bced5e6.png)

**Comment by rockbenben** [comment]
检查网站属性，设置冲突了。本地编辑 ts 时，估计已经报错了

最好是逐步去修改网站，不要一下子动太多。

**Comment by shenzehui** [comment]
呜，在本地是能跑的，但是打包就会报错

**Comment by rockbenben** [comment]
`docs:dev` 会忽略一些错误。

我测试了下，主要是 sidebar 设置报错，你没改全
![image](https://user-images.githubusercontent.com/28252913/199675596-9f3df382-2b70-451b-9715-b9f701069d2b.png)

**Comment by shenzehui** [comment]
我是用这种格式写的
![image](https://user-images.githubusercontent.com/86279988/199676647-78aa5138-b3b5-4dd0-b131-683f5b5674c1.png)

**Comment by shenzehui** [comment]
貌似也没有问题

**Comment by rockbenben** [comment]
结尾多了 `/`
![image](https://user-images.githubusercontent.com/28252913/199677344-a77050a9-1a28-4627-bc2d-11911a89e8a5.png)

先让项目运行起来，再考虑改结构。本地运行 `pnpm docs:build` 看具体报错

**Comment by shenzehui** [comment]
![image](https://user-images.githubusercontent.com/86279988/199699212-4e4d623d-75cd-4cb9-9d16-4f99816b433e.png)
迁移到你的上就好了...，无语了

**Comment by shenzehui** [comment]
找到了 是  "@vuepress/plugin-git": "2.0.0-beta.53"  git 依赖的错

**Comment by shenzehui** [comment]
这个依赖我自己加的，可能是版本问题
