### ISSUE TITLE
不知道为什么哪怕直接用你的项目，我的md生成了网页，很多时候图片预览功能都没有，我把你的图片复制到我的md中也会失效

### ISSUE THREAD

**Issue by dselegent** [rockbenben/LearnData#7]

**Comment by dselegent** [comment]
[这是我的项目地址](https://github.com/dselegent/dselegent-blog)

**Comment by rockbenben** [comment]
页面内容保存在 js 中，估计是页面在读取就缓存。只要不是立即访问，过会再看就没问题。

**Comment by dselegent** [comment]
我发现只要页面滚动条滑到底,然后这个页面所有预览功能都好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月30日(周一) 晚上9:43
收件人: ***@***.***&gt;;
抄送: "State ***@***.******@***.***&gt;;
主题: Re: [rockbenben/LearnData] 不知道为什么哪怕直接用你的项目，我的md生成了网页，很多时候图片预览功能都没有，我把你的图片复制到我的md中也会失效 (Issue #7)




 
页面内容保存在 js 中，估计是页面在读取就缓存。只要不是立即访问，过会再看就没问题。

**Comment by rockbenben** [comment]
刚生成的预览容易读取缓存，实际页面没问题，可以直接看 build 代码，里面有最新页面内容
