### ISSUE TITLE
想请教waline的邮箱通知怎么配置，我按照官网的教程在vercel中添加了环境变量，可是没有用，后面尝试使用了微信通知，可是通知内容是html源码，所以还是想设置成邮箱通知

### ISSUE THREAD

**Issue by dselegent** [rockbenben/LearnData#8]

**Comment by rockbenben** [comment]
`settings/environment-variables` 核对邮箱变量，设置正确肯定没问题的

**Comment by dselegent** [comment]
![image-20230130221805222](https://i0.hdslb.com/bfs/new_dyn/783d057a7ff96ca0be88e70e327ad2ca95443509.png)
![i](https://i0.hdslb.com/bfs/new_dyn/0082d13dad7827d8a1e908e18caf37b595443509.png)
![2](https://i0.hdslb.com/bfs/new_dyn/1ed0b5db2d8787428c523f13339677e795443509.png)
能帮我看下嘛

**Comment by rockbenben** [comment]
`SMTP_SECURE` 删掉，与 service 重复了

**Comment by dselegent** [comment]
> `SMTP_SECURE` 删掉，与 service 重复了

还是收不到邮件通知

**Comment by dselegent** [comment]
> 换一个邮箱服务。不用 servise，设这四个试试 ![image](https://user-images.githubusercontent.com/28252913/215512647-f8b6dc3b-1108-400a-b06a-a69e07defc56.png)

也不行，请问一下你是用的哪种通知

**Comment by rockbenben** [comment]
飞书、qq、gmail 之前都试过，换换看

**Comment by dselegent** [comment]
我刚去官方的评论区看了下，把其它通知的变量都删了，果然有邮件通知了
