### ISSUE TITLE
博客小白一枚，想请教一下本地运行这个库的时候，pnpm i && pnpm up出现了一个warning，后面就没法本地生成网页了，具体报错如下

### ISSUE THREAD

**Issue by Muyky** [rockbenben/LearnData#9]
1.WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

2. 报错：Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'vuepress-plugin-sass-palette' imported from E:\blog\testblo
g\node_modules\.pnpm\registry.npmmirror.com+vuepress-plugin-search-pro@2.0.0-beta.163_e7jwb2ulu5orbkux7obq5onf
au\node_modules\vuepress-plugin-search-pro\lib\node\index.js

前段时间还没有问题，今天突然就不行了，怀疑是不是版本的问题

**Comment by rockbenben** [comment]
改了依赖环境吧，删掉主目录下的 `.npmrc`

**Comment by Muyky** [comment]
谢谢大佬，已解决！
